# Generated by Django 4.1.1 on 2022-09-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='file_slug',
        ),
    ]
