# Generated by Django 4.1.1 on 2022-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
