# Generated by Django 4.1.1 on 2022-09-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_file_slug_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='copy_link',
            field=models.CharField(default='not created', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
